Fix/pubsub webhook tiny
ecomplus/app-tiny-erp pull request #130
Opened 2022-12-01 15:11 UTC by wisley7l

2022-12-01 17:29 UTC, leomp12 requested changes

2022-12-01 17:29 UTC, leomp12 commented on functions/routes/tiny/webhook.js
>              }
Na verdade a intenção é justamente não precisar buscar o data do app no webhook..
Se o Tiny enviar várias requests simultâneas várias vezes você vai bater a Store API, até que ela bloqueie por rate limit, aí dá a resposta de erro e falha a request 😬

2022-12-01 17:29 UTC, leomp12 commented on functions/routes/tiny/webhook.js
>              }
A intenção é que a função HTTP do webhook não faça nada além do push no tópico do PubSub

2022-12-01 17:29 UTC, leomp12 commented on functions/routes/tiny/webhook.js
> +              appClient,
O `appData` nem deveria existir aqui e o `appClient` vai ter funções que não podem ser parseadas para JSON 😛

2022-12-01 17:29 UTC, leomp12 commented on functions/routes/tiny/webhook.js
> +              appClient,
Tanto o `appData` quanto o `appClient` passam a ser criados na função chamada pelo PubSub em vez daqui...

2022-12-01 17:29 UTC, leomp12 commented on functions/lib/pubsub/webhook-tiny.js
> +    appClient,
```suggestion
```

2022-12-01 17:29 UTC, leomp12 commented on functions/lib/pubsub/webhook-tiny.js
> +  appClient.appSdk = appSdk
Na verdade tinha que setar o `appClient` inteiro aqui...

2022-12-01 17:29 UTC, leomp12 commented on functions/lib/pubsub/webhook-tiny.js
> +  appClient.appSdk = appSdk
Primeiro buscar o `appData`, checar o token, aí setar o `appClient`, tudo nessa função

2022-12-01 17:29 UTC, leomp12 commented on functions/lib/pubsub/webhook-tiny.js
> +        }
Isso aqui não era pra existir mais, o retry do pubsub faria essa função bem melhor

2022-12-01 17:29 UTC, leomp12 commented on functions/lib/pubsub/webhook-tiny.js
> +        }
Aliás a intenção de usar PubSub é justamente por isso

2022-12-01 17:29 UTC, leomp12 commented on functions/lib/pubsub/webhook-tiny.js
> +        }
O fallback com `saveToQueue` na verdade deveria passar a ser um error throw pro PubSub fazer outra tentativa

2022-12-01 17:29 UTC, leomp12 commented on functions/lib/pubsub/create-topic.js
> +
```suggestion
```

2022-12-01 21:32 UTC, wisley7l commented
@leomp12 crie a sequinte função no lugar da `saveToQueue`
```
const launchRetry = (err) => {
  if (err) {
     console.error(err)
     return reject(err)
  }
  return reject(new Error(`Unexpected error=> ${context.eventId}`))
}
```

Porém em alguns tests que realizei aqui, o pub/Sub retorna seguinte mensagem 
`Exception from a finished function: Error: XXXX`

e acaba não realizando novas tentativas :cry: , tem algo mais que está errado, ou essa função para lancar o erro não se resolve dessa forma?

2022-12-02 22:18 UTC, leomp12 commented
> Porém em alguns tests que realizei aqui, o pub/Sub retorna seguinte mensagem
Exception from a finished function: Error: XXXX
e acaba não realizando novas tentativas cry , tem algo mais que está errado, ou essa função para lancar o erro não se resolve dessa forma?

O log era o esperado mesmo.
Rejeitar uma função sem catch dá um unhanded exception, e fatal error, até aí tudo certo, sobre não ter retentativa, você tá testando isso onde? Não é alguma limitação de conta talvez? 🤔

2022-12-02 22:19 UTC, leomp12 commented
Tá dando erro aí no função do Pub/Sub mesmo né? Não na função HTTP do webhook do Tiny, certo?

2022-12-03 15:09 UTC, wisley7l commented
Então os testes foram feitos isolados em uma conta que tenho do Firebase e uma conta q criei no tiny. 
Testei a importação e exportação e funcionam corretamente,  e pra forcar o erro eu alterei a URL que bate a StoreApi 

Para ser mais exato aqui:
https://github.com/ecomplus/app-tiny-erp/blob/475fd038060e2ff9351b86765e27f5e1c2478ac5/functions/lib/integration/import-product.js#L151

Mudei o `.json`, para `.jso`, forcando um erro.

2022-12-03 18:46 UTC, leomp12 commented
Certo, e tem certeza que não teve retentativa? Tira um print dos logs no período próximo desse teste e joga aqui por favor, acho que vai facilitar ...

2022-12-04 12:19 UTC, wisley7l commented
![ontiny-1](https://user-images.githubusercontent.com/33531578/205489884-cac34677-e3a6-4c6b-8e7e-07f3d75d720c.png)



![ontiny-2](https://user-images.githubusercontent.com/33531578/205489996-521c0299-f4c2-439f-95ff-6700b7b2096a.png)

2022-12-04 21:58 UTC, leomp12 commented
Não encerrou a função com erro, por isso não teve retentativa.
Tiveram logs da mesma execução na sequência, só bateu um `console.error` da request que falhou:
https://github.com/ecomplus/app-tiny-erp/blob/master/functions/lib/integration/import-product.js#L163
https://github.com/ecomplus/app-tiny-erp/blob/master/functions/lib/integration/import-product.js#L197

2022-12-04 22:02 UTC, leomp12 commented
Nem toda request nos processos de importação/exportação dão error throw, nem deveriam na verdade.
O `catch` no `importProduct` por exemplo seria útil somente em casos de rate limit ou algum erro 5xx de uma das APIs, um erro não mapeado ou um client error só deve ir pra log, sem colocá-lo de volta à fila (retentativa) porque nesse último caso os erros só seriam fixados depois de correção do código, ou seja, se eles resultassem em retentativa geraria um loop infinito.

2022-12-04 22:05 UTC, leomp12 commented
O jeito mais fácil de você testar retentativa seria falhar o `getAppData` na função da PubSub, ou então teria que ver em qual ponto a função de importação daria throw e portanto bateria o catch ali..

2022-12-04 22:09 UTC, leomp12 commented on functions/lib/pubsub/webhook-tiny.js
> +                }
Sobre esse `launchRetry`, na verdade não precisava disso não 🙃 
Só de não ter `.catch(...)` em caso de rejeição da promise a função seria encerrada com erro fatal e teria registro em log, é o que queremos..
Quando você faz:

```js
console.error(err)
return reject(err) // sem catch nesse reject
```

o erro é registrado duas vezes...

2022-12-04 22:09 UTC, leomp12 commented on functions/lib/pubsub/webhook-tiny.js
> +                }
Funciona, mas tem um código excedente aí sem necessidade, e os logs de erro serão duplicados

2022-12-04 22:11 UTC, leomp12 commented on functions/lib/pubsub/webhook-tiny.js
> +                  launchRetry(err)
Ainda sobre não precisar do `launchRetry`:

```suggestion
                  throw err
```

2022-12-04 22:11 UTC, leomp12 commented on functions/lib/pubsub/webhook-tiny.js
> +                .catch(launchRetry)
```suggestion
```

2022-12-05 21:08 UTC, leomp12 approved these changes
valeu valeu

2022-12-05 21:08 UTC, leomp12 commented on functions/lib/integration/import-product.js
@wisley7l né? 😬

2022-12-05 21:09 UTC, merged

2022-12-05 21:55 UTC, wisley7l commented on functions/lib/integration/import-product.js
Sim, sim, foi uma correção automatica inclusive quando usei `ctrl + s`, pq foi qui nesse arquivo que estava testanto para tentar forçar os erros. 

Ai como fez a correção da identação, ai aproveitei e realizei o commit.