chore(import-categories): import categories from tiny
ecomplus/app-tiny-erp pull request #160
Opened 2024-07-01 20:18 UTC by wisley7l

2024-07-03 21:29 UTC, leomp12 requested changes

2024-07-03 21:29 UTC, leomp12 commented on functions/ecom.config.js
> +        description: 'Habilita importação de categorias sempre que um produto novo é criado no Tiny'
É só em produto novo mesmo? 🤔 
Alterando as categorias no ERP, não importa?

2024-07-03 21:29 UTC, leomp12 commented on functions/lib/integration/import-product.js
> +                    const { arvoreCategoria } = tinyStockUpdate
Se certificou que esse objeto `tinyStockUpdate` vai trazer as categorias? Ele é (em alguma ocasião) o body recebido do webhook do Tiny?

2024-07-03 21:29 UTC, leomp12 commented on functions/lib/integration/import-category.js
> +    if (categories && Array.isArray(categories)) {
`Array.isArray(categories)` é redundante aqui mas tá valendo 😃

2024-07-03 21:29 UTC, leomp12 commented on functions/lib/integration/import-category.js
> +    if (categories && Array.isArray(categories)) {
```suggestion
    if (categories && Array.isArray(categories)) {
      hasRepeat = categories.length === limit
```

2024-07-03 21:29 UTC, leomp12 commented on functions/lib/integration/import-category.js
> +    if (categories && Array.isArray(categories)) {
Pra evitar que a request seja duplicada, na grande maioria das lojas já vai buscar tudo na primeira listagem

2024-07-03 21:29 UTC, leomp12 commented on functions/lib/integration/import-category.js
> +  return categoriesAll
Nesse codebase é o menor dos problemas, mas seria _get all categories_ né...

2024-07-03 21:29 UTC, leomp12 commented on functions/lib/integration/import-category.js
> +            })
Aí não faz sentido você ter buscado todas as categorias antes haha

2024-07-03 21:29 UTC, leomp12 commented on functions/lib/integration/import-category.js
> +            })
Se você precisa do metafield, liste todas as categorias já com os metafields

2024-07-03 21:29 UTC, leomp12 commented on functions/lib/integration/import-category.js
> +    })
Oloko kkk

2024-07-03 21:29 UTC, leomp12 commented on functions/lib/integration/import-category.js
> +    })
PATCH `products/id` { categories }

2024-07-03 21:29 UTC, leomp12 commented on functions/lib/integration/import-category.js
> +    })
Um PATCH apenas, sem esse loop haha

2024-07-04 17:02 UTC, wisley7l commented on functions/lib/integration/import-product.js
> +                    const { arvoreCategoria } = tinyStockUpdate
É sim
https://github.com/ecomplus/app-tiny-erp/blob/4c72cb0df98cf2cb0f68a24292865a86ed911183/functions/lib/pubsub/webhook-tiny.js#L70-L80

https://github.com/ecomplus/app-tiny-erp/blob/4c72cb0df98cf2cb0f68a24292865a86ed911183/functions/lib/pubsub/webhook-tiny.js#L83-L85

https://github.com/ecomplus/app-tiny-erp/blob/4c72cb0df98cf2cb0f68a24292865a86ed911183/functions/lib/pubsub/webhook-tiny.js#L94

mas tem um detalhe faltando, vi aqui mas corrigi, que o `arvoreCategorias` fica dentro do objeto `produto`

2024-07-04 17:08 UTC, wisley7l commented on functions/ecom.config.js
> +        description: 'Habilita importação de categorias sempre que um produto novo é criado no Tiny'
Acredito que não é importado se alterar  a categoria, so se essa alteração no ERP foi considerado uma alteração de produto, mas isso não é descrito na documentação. 

Na documentação tem somente essa lista de Webhooks disponíveis

* Atualizações de estoque
* Envio de produtos
* Envio de código de rastreio
* Envio de nota fiscal
* Envio de preços de produtos
* Atualizações de situação de pedido
* Busca cotações de fretes

2024-07-04 20:25 UTC, leomp12 commented on functions/ecom.config.js
> +        description: 'Habilita importação de categorias sempre que um produto novo é criado no Tiny'
Mas o _envio de produtos_ não é restrito a produtos novos

2024-07-04 20:36 UTC, leomp12 requested changes

2024-07-04 20:36 UTC, leomp12 commented on functions/lib/integration/import-category.js
> +      getCategoriesAll.push(...categories)
https://github.com/ecomplus/app-tiny-erp/pull/160#discussion_r1664823907

2024-07-04 20:36 UTC, leomp12 commented on functions/lib/integration/import-category.js
> +          name: descricao[0].toUpperCase() + descricao.substring(1),
Por que essa mudança no case da string?

2024-07-04 20:36 UTC, leomp12 commented on functions/lib/integration/import-category.js
> +          name: descricao[0].toUpperCase() + descricao.substring(1),
Quer dizer, por que não só `name: descricao` ? 🙃

2024-07-04 20:36 UTC, leomp12 commented on functions/lib/integration/import-category.js
> +          delete newCategory.metafields
Não pode deletar o `metafields`, você precisa dele no objeto nas outras interações desse loop

2024-07-04 20:36 UTC, leomp12 commented on functions/lib/integration/import-category.js
> +        delete categories.metafields
`categories` é um array, ainda que não fosse, removendo o `metafields` do objeto da categoria (por referência) ela não vai ser encontrada depois se for parente de alguma outra, não é isso?

2024-07-04 20:36 UTC, leomp12 commented on functions/lib/integration/import-category.js
> +          categories.push(newCategory)
```suggestion
          const { _id, name, slug } = newCategory
          categories.push({ _id, name, slug })
```

2024-07-05 16:56 UTC, leomp12 requested changes

2024-07-05 16:56 UTC, leomp12 commented on functions/ecom.config.js
> +        description: 'Habilita importação de categorias ao importar produtos do Tiny'
```suggestion
        title: 'Importar categorias',
        description: 'Habilita importação de categorias em produtos enviados do Tiny'
```

2024-07-05 16:56 UTC, leomp12 commented on functions/lib/integration/import-product.js
> +                          productId = response?.response?.data && response?.response?.data._id
```suggestion
                          productId = response.response?.data?._id
```

2024-07-05 16:56 UTC, leomp12 commented on functions/lib/integration/import-product.js
> +                        if (arvoreCategoria && productId) {
```suggestion
                        const { arvoreCategoria } = tinyStockUpdate.produto
                        if (productId) {
```

Três linhas pra cima já tá checando se `tinyStockUpdate?.produto?.arvoreCategoria`...

2024-07-05 16:56 UTC, leomp12 commented on functions/lib/integration/import-product.js
> +                    const { arvoreCategoria } = tinyStockUpdate?.produto
```suggestion
                    const arvoreCategoria = tinyStockUpdate?.produto?.arvoreCategoria
```

Optional chaining não previne fatal com destruição de objeto

2024-07-05 16:56 UTC, leomp12 commented on functions/lib/integration/import-product.js
> +                    const { arvoreCategoria } = tinyStockUpdate?.produto
Quer dizer, se `tinyStockUpdate?.produto` for undefined daria erro no seu código

2024-07-05 16:56 UTC, leomp12 commented on functions/lib/integration/import-product.js
> +const { response } = require('express')
```suggestion
```

Sem querer né?

2024-07-05 16:56 UTC, leomp12 commented on functions/lib/integration/import-category.js
> +          .catch(e => null)
Ué haha

2024-07-05 16:56 UTC, leomp12 commented on functions/lib/integration/import-category.js
> +          .catch(e => null)
Bota um logger aí nesse catch pelo menos

2024-07-05 20:24 UTC, leomp12 commented on functions/lib/integration/import-category.js
> +      })
```suggestion
      .catch(console.error)
```

2024-07-05 23:33 UTC, leomp12 approved these changes
lgtm 🎉

2024-07-08 16:16 UTC, merged